/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import javax.swing.JFrame;
import MyLibs.*; 
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Brey
 */
public class AddDoctorPage extends javax.swing.JFrame implements FormCommand{

    /**
     * Creates new form AddDoctorPage
     */
    
    //ImageIcon icon = new ImageIcon("CodePrototype_Final_withDB_WithUI/src/images/capture.png");
 //AddDoctorPage.setIconImage(icon.getImage());
    public AddDoctorPage() {
        initComponents();
       // setIcon();
        //new javax.swing.ImageIcon(getClass(),getResource("/CodePrototype_Final_withDB_WithUI/src/images/capture.png")).getImage();
        ImageIcon icon = new ImageIcon("C:\\Users\\AUBREY MARIE\\Desktop\\New folder (2)\\CodePrototype_Final_withDB_WithUI\\src\\images\\icons.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addDoctorSpecialization = new javax.swing.JComboBox<>();
        docname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Homes = new javax.swing.JButton();
        submits = new javax.swing.JButton();
        clears = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        timePicker3 = new com.raven.swing.TimePicker();
        timePicker4 = new com.raven.swing.TimePicker();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 30)); // NOI18N
        jLabel3.setText("ADD NEW DOCTOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 290, 50));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Name of Doctor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("Rate:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 50, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setText("Schedule");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 238, 80, 30));

        addDoctorSpecialization.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addDoctorSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Dermatologist", "Urologist", "Pediatrician", "Cardiologist" }));
        getContentPane().add(addDoctorSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 170, -1));
        getContentPane().add(docname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 360, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setText("Day From:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 110, 30));

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel11.setText("Time From:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 276, -1, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("Time To:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 280, 80, 20));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setText("Day To:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 80, 30));

        Homes.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        Homes.setText("HOME");
        Homes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomesActionPerformed(evt);
            }
        });
        getContentPane().add(Homes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 110, 50));

        submits.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        submits.setText("SUBMIT");
        submits.setToolTipText("");
        submits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitsActionPerformed(evt);
            }
        });
        getContentPane().add(submits, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 110, 40));

        clears.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        clears.setText("CLEAR");
        clears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearsActionPerformed(evt);
            }
        });
        getContentPane().add(clears, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cs project logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Specialization:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 30));

        rateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateFieldActionPerformed(evt);
            }
        });
        rateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(rateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 230, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 130, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 130, 30));
        getContentPane().add(timePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));
        getContentPane().add(timePicker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proj_background.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 730, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proj_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 730, 430));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proj_background.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitsActionPerformed
        // TODO add your handling code here:
     //   if(addDoctorSpecialization.getSelectedItem())
     JFrame parent = new JFrame();
     boolean correct = false;
     
        
        String doctorName = docname.getText();   
        String rates = rateField.getText();
        String time = timePicker4.getSelectedTime();
        String time2 = timePicker3.getSelectedTime();
        String day = jComboBox1.getSelectedItem().toString();
        String day2 = jComboBox3.getSelectedItem().toString();
      //To check if the user has input the important details
      if(doctorName.equals("")){
          JOptionPane.showMessageDialog(null, "Doctor's name is required");
      } 
      else if(addDoctorSpecialization.getSelectedIndex() == 0){
          JOptionPane.showMessageDialog(null, "Specialization is required");
      }
      else if(rates.equals("")){
          JOptionPane.showMessageDialog(null, "Time of the schedule is required");
      }
      
      else{
          correct = true;
      }
      
     if(correct == true) {
         HospitalFactory hospitalFactory = new HospitalFactory();
        Hospital specialize = hospitalFactory.spec(addDoctorSpecialization.getSelectedItem().toString());
        if(addDoctorSpecialization.getSelectedIndex() == 1){
            //  JFrame parent = new JFrame();
              Hospital dermatologist = hospitalFactory.spec("Dermatologist");                          
                               //dermatologist.addDoctor(doctorName);
                              //  dermatologist.addSchedule(doctorName, day, day2, time, time2);                               
                                specialize.addDoctor(doctorName);
                                specialize.addSchedule(doctorName,rates, day, day2, time, time2);
                                 // JOptionPane.showMessageDialog(parent,"Doctor Added");
                            }
          
          else if(addDoctorSpecialization.getSelectedIndex() == 2){
           //   JFrame parent = new JFrame();
             // Hospital urologist = hospitalFactory.spec("urologist");
                                  specialize.addDoctor(doctorName);
                                  specialize.addSchedule(doctorName,rates, day, day2, time, time2);
                                 // JOptionPane.showMessageDialog(parent,"Doctor Added");
                                      }
          else if(addDoctorSpecialization.getSelectedIndex() == 3){
            //  JFrame parent = new JFrame();
            //  Hospital pediatrician = hospitalFactory.spec("pediatrician");
                            specialize.addDoctor(doctorName);
                            specialize.addSchedule(doctorName,rates, day, day2, time, time2);
                        //    JOptionPane.showMessageDialog(parent,"Doctor Added");
                            }
          
          else if(addDoctorSpecialization.getSelectedIndex() == 4){
            //  JFrame parent = new JFrame();
          //    Hospital cardiologist = hospitalFactory.spec("cardiologist");
                               specialize.addDoctor(doctorName);
                              
                               specialize.addSchedule(doctorName,rates, day, day2, time, time2);
                             //     JOptionPane.showMessageDialog(parent,"Doctor Added");
                               
                               
                            }
        docname.setText(null);  
        addDoctorSpecialization.setSelectedIndex(0);
        rateField.setText(null);
        
        correct = false;
     }
    }//GEN-LAST:event_submitsActionPerformed

    private void HomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomesActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();

    home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    //login.setSize(800, 600);
    home.setVisible(true);
    home.setLocationRelativeTo(null);

    home.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_HomesActionPerformed

    private void clearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearsActionPerformed
        // TODO add your handling code here:
        docname.setText(null);  
        addDoctorSpecialization.setSelectedIndex(0);
        rateField.setText(null);
    }//GEN-LAST:event_clearsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void rateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateFieldKeyTyped
        
        char c = evt.getKeyChar();
     if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
         getToolkit().beep();
         evt.consume();
        
     }
    }//GEN-LAST:event_rateFieldKeyTyped

    private void rateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateFieldActionPerformed

    public void execute(){
        this.setVisible(true);
        
       this.pack();
       this.setLocationRelativeTo(null);
       this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pic.png")));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Homes;
    private javax.swing.JComboBox<String> addDoctorSpecialization;
    private javax.swing.JButton clears;
    private javax.swing.JTextField docname;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rateField;
    private javax.swing.JButton submits;
    private com.raven.swing.TimePicker timePicker3;
    private com.raven.swing.TimePicker timePicker4;
    // End of variables declaration//GEN-END:variables
}
