/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import javax.swing.JFrame;

/**
 *
 * @author Brey
 */
public class ConsultationHistoryPage extends javax.swing.JFrame implements FormCommand{

    /**
     * Creates new form PatientsPage
     */
    public ConsultationHistoryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        HistoryHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 30)); // NOI18N
        jLabel3.setText("Consultation History");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 20, 290, 80);

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Doctor", "Patient", "Fee"
            }
        ));
        jScrollPane1.setViewportView(HistoryTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 160, 350, 170);

        HistoryHome.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        HistoryHome.setText("HOME");
        HistoryHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryHomeActionPerformed(evt);
            }
        });
        getContentPane().add(HistoryHome);
        HistoryHome.setBounds(620, 70, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cs project logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 200, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proj_background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoryHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryHomeActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();

    home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    //login.setSize(800, 600);
    home.setVisible(true);
    home.setLocationRelativeTo(null);

    home.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_HistoryHomeActionPerformed

    
    public void execute(){
        this.setVisible(true);
        
       this.pack();
       this.setLocationRelativeTo(null);
       this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationHistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationHistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationHistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationHistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultationHistoryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistoryHome;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
