/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import MyLibs.DeleteConsult;
import MyLibs.DeleteDocConsult;
import MyLibs.DeleteDoctor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author johnp
 */
public class DeleteForm extends javax.swing.JFrame implements FormCommand{

    /**
     * Creates new form DeleteForm
     */
    public DeleteForm() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\AUBREY MARIE\\Desktop\\New folder (2)\\CodePrototype_Final_withDB_WithUI\\src\\images\\icons.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        DeleteDoc = new javax.swing.JButton();
        DeleteConsult = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BackHomes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setText("Patient Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 50));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 30)); // NOI18N
        jLabel8.setText("Delete Form");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 50));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setText("Doctor Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("Delete Doctor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, 30));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setText("Delete Consultation");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, 50));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 160, 40));

        DeleteDoc.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        DeleteDoc.setText("Delete Doctor");
        DeleteDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDocActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, 50));

        DeleteConsult.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        DeleteConsult.setText("Delete Consultation");
        DeleteConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteConsultActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cs project logo.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 70));

        BackHomes.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        BackHomes.setText("HOME");
        BackHomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomesActionPerformed(evt);
            }
        });
        getContentPane().add(BackHomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proj_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 729, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDocActionPerformed
        
        String docname = jTextField1.getText();
        
        DeleteDocConsult Doc = new DeleteDoctor();
        
        Doc.Delete(docname);
        JOptionPane.showMessageDialog(null, "Doctor Deleted");
        jTextField1.setText("");
        
    }//GEN-LAST:event_DeleteDocActionPerformed

    private void DeleteConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteConsultActionPerformed
        
        String consultname = jTextField2.getText();
        
        DeleteDocConsult cons = new DeleteConsult();
        
        cons.Delete(consultname);
        JOptionPane.showMessageDialog(null, "Consultation Deleted");
        jTextField2.setText("");
    }//GEN-LAST:event_DeleteConsultActionPerformed

    private void BackHomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomesActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();

        home.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //login.setSize(800, 600);
        home.setVisible(true);
        home.setLocationRelativeTo(null);

        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackHomesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void execute(){
       this.setVisible(true);
        
       this.pack();
       this.setLocationRelativeTo(null);
       this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHomes;
    private javax.swing.JButton DeleteConsult;
    private javax.swing.JButton DeleteDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
